### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by X-Hellfire-X** [Benjamin-Norton/Neruina#45] opened 2024-02-24 20:59 UTC
[debug.log](https://github.com/Bawnorton/Neruina/files/14394421/debug.log)

**Comment by Bawnorton** [comment] 2024-02-24 21:00
Duplicate of #37

**Closed as not planned by Bawnorton** 2024-02-24 21:00 UTC

**Comment by X-Hellfire-X** [comment] 2024-02-24 21:02
I am not on forge 47.2.20

**Comment by Bawnorton** [comment] 2024-02-24 21:03
yes you are
`[cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.2.20, --fml.mcVersion, 1.20.1, --fml.forgeGroup,`
(from your log)

**Comment by X-Hellfire-X** [comment] 2024-02-24 21:04
but it said it was .18 in the jar install panel
