### ISSUE TITLE
Game Crashed by Critical Injection Failure with Forge 1.20.1 - 47.2.20

### ISSUE THREAD

**Issue by Coraline774477** [Benjamin-Norton/Neruina#37] opened 2024-01-14 02:22 UTC
Minecraft: 1.20.1
Forge: 47.2.20
Neruina - Ticking Entity Fixer: 1.3.0

After updating Forge to Forge 1.20.1-47.2.20 which fixed the missing patch for Item.InventoryTick that obviously breaks Neruina's common.mixins.json:PlayerInventoryMixin in the embedded core mod ExtraMixins.

When the game crashed there's no crash report BUT there is a log, so here's the log:

Log: https://gist.github.com/Coraline774477/3e4338ad52a4cd0be5a9dfbc458fa403

One more thing, since Lex may have fixed something that Neruina had fixed prier to 47.2.20 that whatever your patch was is possibly no longer needed and needs to be removed for 47.2.20 and newer.
So for now I'll be downgrading forge to the previous version (47.2.19) till you resolve this issue with an update.
Luckily I always keep the previous version of forge installed in my launcher for circumstances like this.
Since I need this mod for circumstances with ticking entities from other mods or even the game itself sometimes when Mojang messes up something in one of the updates.
Which means this mod is a crucial/vital performance mod for potentially fixing ticking entities, since I had ticking entity crashes before and they're not fun at all..

**Comment by Bawnorton** [comment] 2024-01-14 02:25
This log is truncated

**Comment by Coraline774477** [comment] 2024-01-14 02:27
Truncated?

**Comment by Bawnorton** [comment] 2024-01-14 02:28
Most of it is cut-off, there is no useful information in the portion you sent

**Comment by Coraline774477** [comment] 2024-01-14 02:29
Oh, now I know what it means, why though is cause the game crashed at the very beginning so the game didn't have enough time to log past where it crashed

**Comment by Coraline774477** [comment] 2024-01-14 02:30
Wtf? It is shorter than the one I saw when I was brought back to the launcher. However I read the one I saw and it had the vital info about a mixin that broke from Lex's fix in the latest version of Forge 1.20.1.
I guess I'll need to let the game crash again so that I can copy the text and paste it in a new secret gist and send it here

**Comment by Coraline774477** [comment] 2024-01-14 03:04
Here's what I saw, I had to let the game crash again to get the popup that has a few options and one let's me open the logs and this is what showed up: https://gist.github.com/Coraline774477/f5376d5c228083a7a9db748500fd82f2

I had to physically copy and paste all of the text into that gist

**Comment by Bawnorton** [comment] 2024-01-14 03:09
Ok I'll look into what forge is doing in more recent versions. This will likely get bundled with the next version I am working on which will release when 1.20.5 releases

**Comment by Coraline774477** [comment] 2024-01-14 03:11
That's great and all to hear but I ain't moving away from 1.20.1 just yet but I don't know if my current laptop can handle 1.20.4 and newer which is partially the reason why I remained on 1.20.1 for this long..

Btw what I meant by "Popup" was this: ![Screenshot (96)](https://github.com/Bawnorton/Neruina/assets/108352241/5fffd415-4b2a-4149-8f38-fe8dfe5bfc58)


Thanks anyways for taking the time to review my report as well as potentially taking a look at this and what forge is doing in more recent versions. Even if the fix is aimed for 1.20.4/5, plus I didn't felt like updating forge 1.20.1 to 47.2.20 anyways and now I have an actual reason not to update it so that I can continue to use this on 1.20.1. BUT that fix that Lex did might help with performance to some degree though..

Oh! One very last thing, even though I use TL Legacy (in the screenshot) for modded minecraft but I do have an official copy as a redeem thing from a friend on discord several years ago. Just letting you know about that but why use TL Legacy? Because of performance reasons and it has less background processes than the official launcher does anyways.

**Comment by Bawnorton** [comment] 2024-01-14 04:04
I will aim to maintain full backwards compat for neruina back to 1.18.2 for future releases, provided that it is feasible

**Comment by itsdinkd** [comment] 2024-01-18 03:31
Same happens to me on my pack im building, the log contains absolutely nothing useful. It crashes way too soon in the start up process without any indication however when binary searching. it came down to this mod.

i know you said youll look into it but just adding to the thread.

**Comment by itsdinkd** [comment] 2024-01-18 03:34
AH this is why, most likely.

Forge 47.4.20 added this
"- 47.2.20 Fix missing patch for Item.onInventoryTick. Closes #9812"

**Comment by Coraline774477** [comment] 2024-01-19 03:43
> AH this is why, most likely.
> 
> Forge 47.4.20 added this "- 47.2.20 Fix missing patch for Item.onInventoryTick. Closes #9812"

I've already noted about that above, as he stated that the fix may be back ported to forge 1.20.1.

You have seen all of this conversation between me and Bawnorton, right?

**Comment by jmadarg** [comment] 2024-02-09 02:26
Any update on this? ATM9 got updated recently to 47.2.20 and the servers I help running had some Ticking Entity crashes already (they were updated last night)

**Comment by Bawnorton** [comment] 2024-02-09 02:30
I'll release when 1.20.5 is released as my current dev branch is intended to release for forge, neoforge and fabric at the same time, which should be in a few weeks. ATM is a forge pack and you can use the config located at `<world>/serverconfig/forge-server.toml` and turn on `removeErroringEntities` in the meantime

**Comment by LKAice** [comment] 2024-02-10 19:13
> Any update on this? ATM9 got updated recently to 47.2.20 and the servers I help running had some Ticking Entity crashes already (they were updated last night)

i had a simmilar problem, whatever i did, anything with forge 47.2.20 wasn't starting. At least thats what i thought. ATM 9 was running perfectly fine if i startet it trough ATLauncher. So its probably something with curseforge, havent figured it out yet

**Comment by LKAice** [comment] 2024-02-10 19:16
> > Any update on this? ATM9 got updated recently to 47.2.20 and the servers I help running had some Ticking Entity crashes already (they were updated last night)
> 
> i had a simmilar problem, whatever i did, anything with forge 47.2.20 wasn't starting. At least thats what i thought. ATM 9 was running perfectly fine if i startet it trough ATLauncher. So its probably something with curseforge, havent figured it out yet

ok, a complete reinstall of curseforge including all cashes etc. and a fresh install of Curseforge / the monecraft plugin and the pack did the trick

DONT FORGET TO BACKUP YOUR SAVES AND OTHER PACKS!

**Comment by jmadarg** [comment] 2024-02-10 19:59
@LKAice I'm not sure what you are talking about. The incompatibility of Neruina and Forge 47.2.20 is confirmed and servers will simply not start if they have that combination.
The ticking entity crashes are something expected to happen from time to time in a modded environment, specially on servers with high playercount, and Neruina prevents them. As currently Neruina can't be used for 47.2.20 some ticking entity crashes may happen, which is the issue I have

**Comment by katubug** [comment] 2024-02-20 22:06
As someone also having this issue, I just wanted to pop in and say thank you to everyone for helping to work this out! Especial thanks to Bawnorton for maintaining so many versions of the mod.

**Comment by X-Hellfire-X** [comment] 2024-02-24 21:04
I am crashing yet im on forge 47.2.18

**Comment by X-Hellfire-X** [comment] 2024-02-24 21:28
is there any way to fix it?

**Comment by KhaosKhaos** [comment] 2024-04-06 04:41
Any news?

**Comment by Bawnorton** [comment] 2024-04-06 04:45
Nothing changed, as mentioned above. I will be releasing the update that supports this when 1.20.5 is released as it is a complete overhaul of the mod. 
I have more testing to do for the upcoming features and this time-gap gives me some breathing room. 

https://github.com/Bawnorton/Neruina/blob/stonecutter/CHANGELOG.md

**Comment by KhaosKhaos** [comment] 2024-04-06 18:40
Cool btw great mod dude <3 thx a loooooooooooot

**Comment by Coraline774477** [comment] 2024-04-30 04:07
I wonder if I really was the first to report about this problem before everyone else started having the same problem weeks after I did when I updated to what was the latest version of forge 1.20.1 at the time (47.2.20).

Since it's been a little more than three months now at 47.2.30.

Knock on wood that I continue not to encounter any ticking entities but so far so good that I haven't ran into any for the past few months since I stopped using Neruina till it's 2.0 release in May which 1.20.5 is right around the corner now.

**Comment by Bawnorton** [comment] 2024-05-13 20:12
Fixed in 2.0.0-beta.1

**Closed as completed by Bawnorton** 2024-05-13 20:12 UTC

**Comment by Coraline774477** [comment] 2024-06-03 07:26
Yay! 2.0.0 (as of its 10th beta) is finally here! Can't wait to eventually get my hands on a copy of Neruina - 2.0.0 in full release or when it's stable enough. Also still knocking on wood that I still haven't ran into any ticking entities yet.

However, what I've been being bombarded with is bad server lag (TPS) for the past few months to more than 5 months now due to newer forge versions that Lex may have snuck in some fix or something that's causing most mods that were playable to now be unbearable to play with due the immense amount of server lag, such as GPU Memory Leak Fix causing high server lag when installed which that mod's being counterproductive to what it's supposed to be doing. That mod is making things worse than making things better for me..
