### ISSUE TITLE
Animation Indexing

### ISSUE THREAD

**Issue by itsdeadfrosty** [Benjamin-Norton/Neruina#114] opened 2024-11-02 10:08 UTC
[latest.log](https://github.com/user-attachments/files/17606483/latest.log)

Error: IndexOutOfBoundsException in animation handling, especially on tick entities.
Impact: May lead to unexpected client behavior during animation playback for specific entities.
Potential Conflict: Seen with player-animation-lib, which may require compatibility checking.

**Comment by Bawnorton** [comment] 2024-11-02 14:18
Duplicate of #115

**Closed as not planned** 2024-11-02 14:19 UTC
