### ISSUE TITLE
Crash on v2.0.0 beta 2 for Fabric 1.20.6

### ISSUE THREAD

**Issue by sternschnaube** [Benjamin-Norton/Neruina#63] opened 2024-05-14 04:39 UTC
Tested just beside Fabric API.

Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/minecraft/class_437
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [minecraft_server.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_437
        at com.bawnorton.neruina.Neruina.<init>(Neruina.java:38) ~[neruina-fabric-2.0.0-beta.2+1.20.6.jar:?]
        at com.bawnorton.neruina.Neruina.<clinit>(Neruina.java:26) ~[neruina-fabric-2.0.0-beta.2+1.20.6.jar:?]
        at net.minecraft.class_1799.handler$zjc000$neruina$readErroredFromComponents(class_1799.java:1653) ~[server-intermediary.jar:?]
        at net.minecraft.class_1799.<init>(class_1799.java:268) ~[server-intermediary.jar:?]
        at net.minecraft.class_1799.<init>(class_1799.java:260) ~[server-intermediary.jar:?]
        at net.minecraft.class_1799.<init>(class_1799.java:244) ~[server-intermediary.jar:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at net.minecraft.class_1856.<init>(class_1856.java:45) ~[server-intermediary.jar:?]
        at net.minecraft.class_1856.method_8092(class_1856.java:103) ~[server-intermediary.jar:?]
        at net.minecraft.class_1856.method_26964(class_1856.java:121) ~[server-intermediary.jar:?]
        at net.minecraft.class_1856.method_8091(class_1856.java:113) ~[server-intermediary.jar:?]
        at net.minecraft.class_7298.<clinit>(class_7298.java:82) ~[server-intermediary.jar:?]
        at net.minecraft.class_5135.<clinit>(class_5135.java:91) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_17598(class_2966.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        ... 4 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at com.bawnorton.neruina.Neruina.<init>(Neruina.java:38) ~[neruina-fabric-2.0.0-beta.2+1.20.6.jar:?]
        at com.bawnorton.neruina.Neruina.<clinit>(Neruina.java:26) ~[neruina-fabric-2.0.0-beta.2+1.20.6.jar:?]
        at net.minecraft.class_1799.handler$zjc000$neruina$readErroredFromComponents(class_1799.java:1653) ~[server-intermediary.jar:?]
        at net.minecraft.class_1799.<init>(class_1799.java:268) ~[server-intermediary.jar:?]
        at net.minecraft.class_1799.<init>(class_1799.java:260) ~[server-intermediary.jar:?]
        at net.minecraft.class_1799.<init>(class_1799.java:244) ~[server-intermediary.jar:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
        at net.minecraft.class_1856.<init>(class_1856.java:45) ~[server-intermediary.jar:?]
        at net.minecraft.class_1856.method_8092(class_1856.java:103) ~[server-intermediary.jar:?]
        at net.minecraft.class_1856.method_26964(class_1856.java:121) ~[server-intermediary.jar:?]
        at net.minecraft.class_1856.method_8091(class_1856.java:113) ~[server-intermediary.jar:?]
        at net.minecraft.class_7298.<clinit>(class_7298.java:82) ~[server-intermediary.jar:?]
        at net.minecraft.class_5135.<clinit>(class_5135.java:91) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_17598(class_2966.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
        ... 4 more

**Comment by Bawnorton** [comment] 2024-05-14 11:50
Hmm. I know I tested 1.20.6, imma see if I can recreate.

**Comment by Bawnorton** [comment] 2024-05-14 12:11
Should be fixed in 2.0.0-beta.3, lmk.

**Comment by venaminecraft** [comment] 2024-05-14 12:18
Testing it now, thanks!

**Comment by venaminecraft** [comment] 2024-05-14 12:21
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/minecraft/class_437
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [minecraft_server.jar:1.0.1]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_437
	at com.bawnorton.neruina.Neruina.<init>(Neruina.java:38) ~[neruina-fabric-2.0.0-beta.3+1.20.6.jar:?]
	at com.bawnorton.neruina.Neruina.<clinit>(Neruina.java:26) ~[neruina-fabric-2.0.0-beta.3+1.20.6.jar:?]
	at net.minecraft.class_1799.handler$epn000$neruina$readErroredFromComponents(class_1799.java:5153) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.<init>(class_1799.java:268) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.<init>(class_1799.java:260) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.<init>(class_1799.java:244) ~[server-intermediary.jar:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at net.minecraft.class_1856.<init>(class_1856.java:45) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8092(class_1856.java:103) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_26964(class_1856.java:121) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8091(class_1856.java:113) ~[server-intermediary.jar:?]
	at net.minecraft.class_7298.<clinit>(class_7298.java:82) ~[server-intermediary.jar:?]
	at net.minecraft.class_5135.<clinit>(class_5135.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_17598(class_2966.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 4 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at com.bawnorton.neruina.Neruina.<init>(Neruina.java:38) ~[neruina-fabric-2.0.0-beta.3+1.20.6.jar:?]
	at com.bawnorton.neruina.Neruina.<clinit>(Neruina.java:26) ~[neruina-fabric-2.0.0-beta.3+1.20.6.jar:?]
	at net.minecraft.class_1799.handler$epn000$neruina$readErroredFromComponents(class_1799.java:5153) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.<init>(class_1799.java:268) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.<init>(class_1799.java:260) ~[server-intermediary.jar:?]
	at net.minecraft.class_1799.<init>(class_1799.java:244) ~[server-intermediary.jar:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?]
	at net.minecraft.class_1856.<init>(class_1856.java:45) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8092(class_1856.java:103) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_26964(class_1856.java:121) ~[server-intermediary.jar:?]
	at net.minecraft.class_1856.method_8091(class_1856.java:113) ~[server-intermediary.jar:?]
	at net.minecraft.class_7298.<clinit>(class_7298.java:82) ~[server-intermediary.jar:?]
	at net.minecraft.class_5135.<clinit>(class_5135.java:91) ~[server-intermediary.jar:?]
	at net.minecraft.class_2966.method_17598(class_2966.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	... 4 more

**Comment by Bawnorton** [comment] 2024-05-14 12:24
Can you send your full latest.log

**Comment by venaminecraft** [comment] 2024-05-14 12:26
[latest.log](https://github.com/Bawnorton/Neruina/files/15308287/latest.log)

**Comment by Bawnorton** [comment] 2024-05-14 13:19
Finally managed to figure out what was going on. Fixed in 2.0.0-beta.4

**Closed as completed by Bawnorton** 2024-05-14 13:19 UTC

**Comment by venaminecraft** [comment] 2024-05-14 18:55
Awesome 🎉
