### ISSUE TITLE
Lost items

### ISSUE THREAD

**Issue by Hiropot** [Benjamin-Norton/Neruina#33] opened 2024-01-06 10:06 UTC
Hello!
Medieval minecraft 1.20.1 v24
I did play yesterday and closed as normal.
but when started the game this morning i got a crash where i lost items from the shulker inventory as well as the entire backpack too
is there a way to restore these?
(included the crash report)
[crash-2024-01-06_10.04.21-server.txt](https://github.com/Bawnorton/Neruina/files/13849125/crash-2024-01-06_10.04.21-server.txt)
I am not very familiar with this regarding this so sorry :'D

**Comment by Bawnorton** [comment] 2024-01-06 20:51
You crashed due to a ticking exception on your player, it was caused by a mod modifying the rewards for an advancement collection before they were loaded. 
The most likely culprits are apotheosis or sinyatra connector, it's hard to tell, forge's stack traces are hard to read.

Neruina doesn't alter any inventories so your inventories wiping is not a result of neruina, the only way to retrieve them would be from a backup of your save folder. 

Neruina did what it was supposed to do so I'm closing this

**Closed as completed by Bawnorton** 2024-01-06 20:51 UTC
